require "open3"
require "json"

SRC_APP = "temari-staging"
DST_APP = "temari-qa"
COPY_KEYS = [
  "API_AUTH_PASSWORD",
  "API_AUTH_USER",
  "IP_WHITE_LIST",
  "MIGRATION_COUPON_ZUORA_PRODUCT_RATE_PLAN_ID",
  "SALES_FORCE_BASE_URL",
  "SAML_CONSUMER_SERVICE_URL",
  "SAML_IDP_CERT",
  "SAML_IDP_ENTITY_ID",
  "SAML_IDP_SLO_TARGET_URL",
  "SAML_IDP_SSO_TARGET_URL",
  "SAML_ISSUER_URL",
  "SECRET_KEY_BASE",
  "SLACK_NOTIFICATE_CHANNEL",
  "SLACK_WEBHOOK_URL",
  "ZUORA_ACCOUNT_URL",
  "ZUORA_API_ACCESS_KEY",
  "ZUORA_API_GET_METHOD_TIMEOUT",
  "ZUORA_API_SECRET_KEY",
  "ZUORA_BANK_TRANSFER_PAYMENT_METHOD_ID",
  "ZUORA_BASE_URL_API",
  "ZUORA_BASE_URL_HOSTED_PAGE_SCRIPT",
  "ZUORA_COMMUNICATION_PROFILE_ID",
  "ZUORA_COUPON_PRODUCT_IDS",
  "ZUORA_CREDIT_CARD_PAYMENT_METHOD_ID",
  "ZUORA_HOSTED_PAGE_PAYMENT_GATEWAY",
  "ZUORA_HOSTED_PAGE_SUPPORTED_TYPES",
  "ZUORA_HOSTED_PAGE_URL",
  "ZUORA_INVOICE_URL",
  "ZUORA_REVENUE_ADJUSTMENT_PRODUCT_RATE_PLAN_CHARGE_ID"
]

o, e, s = Open3.capture3("heroku config -a #{SRC_APP} --json")
env = JSON.parse(o)
COPY_KEYS.each { |key| Open3.capture3("heroku config:set #{key}=#{env[key]} -a #{DST_APP}") }
